class MessageType:
    # Klient -> Serwer
    LOGIN = "LOGIN"
    JOIN_ROOM = "JOIN_ROOM"
    LEAVE_ROOM = "LEAVE_ROOM"
    SEND_MESSAGE = "SEND_MESSAGE"
    MESSAGE_ACK = "MESSAGE_ACK"
    STATUS = "STATUS"
    PING = "PING"
    BYE = "BYE"

    # Serwer -> Klient
    LOGIN_OK = "LOGIN_OK"
    LOGIN_ERR = "LOGIN_ERR"
    ROOM_EVENT = "ROOM_EVENT"
    DELIVER_MESSAGE = "DELIVER_MESSAGE"
    PONG = "PONG"
    ERROR = "ERROR"
    BYE_ACK = "BYE_ACK"

    # Zaproszenia do pokojów prywatnych
    ROOM_INVITE = "ROOM_INVITE"
    ROOM_INVITE_ACCEPT = "ROOM_INVITE_ACCEPT"
    ROOM_INVITE_DECLINE = "ROOM_INVITE_DECLINE"

    # Lista pokojów
    ROOMS_LIST = "ROOMS_LIST"

    # Znajomi
    FRIEND_REQUEST        = "FRIEND_REQUEST"
    FRIEND_REQUEST_ACCEPT = "FRIEND_REQUEST_ACCEPT"
    FRIEND_REQUEST_DECLINE= "FRIEND_REQUEST_DECLINE"
    FRIEND_STATUS_UPDATE  = "FRIEND_STATUS_UPDATE"
    FRIEND_REMOVE         = "FRIEND_REMOVE"

    # Zarządzanie pokojami (admin)
    CREATE_ROOM           = "CREATE_ROOM"
    CREATE_ROOM_OK        = "CREATE_ROOM_OK"
    DELETE_ROOM           = "DELETE_ROOM"
    DELETE_ROOM_OK        = "DELETE_ROOM_OK"
    FRIENDS_LIST          = "FRIENDS_LIST"
    DIRECT_MESSAGE        = "DIRECT_MESSAGE"

    # Lista uczestników pokoju i moderacja (kick/ban)
    ROOM_MEMBERS_REQUEST  = "ROOM_MEMBERS_REQUEST"
    ROOM_MEMBERS_LIST     = "ROOM_MEMBERS_LIST"
    ROOM_KICK             = "ROOM_KICK"
    ROOM_BAN              = "ROOM_BAN"
    ROOM_UNBAN            = "ROOM_UNBAN"
    ROOM_BAN_OK           = "ROOM_BAN_OK"
    ROOM_UNBAN_OK         = "ROOM_UNBAN_OK"
    ROOM_KICK_OK          = "ROOM_KICK_OK"

    ALL = {
        "LOGIN", "JOIN_ROOM", "LEAVE_ROOM", "SEND_MESSAGE", "MESSAGE_ACK",
        "STATUS", "PING", "BYE", "LOGIN_OK", "LOGIN_ERR", "ROOM_EVENT",
        "DELIVER_MESSAGE", "PONG", "ERROR", "BYE_ACK",
        "ROOM_INVITE", "ROOM_INVITE_ACCEPT", "ROOM_INVITE_DECLINE",
        "ROOMS_LIST",
        "FRIEND_REQUEST", "FRIEND_REQUEST_ACCEPT", "FRIEND_REQUEST_DECLINE",
        "FRIEND_STATUS_UPDATE", "FRIENDS_LIST", "DIRECT_MESSAGE",
        "FRIEND_REMOVE",
        "CREATE_ROOM", "CREATE_ROOM_OK",
        "DELETE_ROOM", "DELETE_ROOM_OK",
        "ROOM_MEMBERS_REQUEST", "ROOM_MEMBERS_LIST",
        "ROOM_KICK", "ROOM_BAN", "ROOM_UNBAN",
        "ROOM_BAN_OK", "ROOM_UNBAN_OK", "ROOM_KICK_OK",
        "REGISTER", "REGISTER_OK", "REGISTER_ERR",
    }

    # Rejestracja
    REGISTER      = "REGISTER"
    REGISTER_OK   = "REGISTER_OK"
    REGISTER_ERR  = "REGISTER_ERR"

    # Typy które nie wymagają tokenu sesji
    NO_AUTH_REQUIRED = {"LOGIN", "REGISTER"}